version: "3.9"

services:
  mongodb:
    image: "nabin011011/mongo:v1.0"
    container_name: "mongodb"
    command: ["bin/bash","-c","mongoimport --db wanderlust --collection posts --file sample_posts.json --jsonArray"]
    ports:
      - "27017:27017"
    networks:
      - wanderlust_0
    restart: always

  backend:
    image: "nabin011011/wanderlust-backend:latest"
    container_name: "backend"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - CORS_ORIGIN=http://52.66.245.164:5173
      - FRONTEND_URL=http://52.66.245.164:5173
    ports:
      - "5000:5000"
    networks:
      - wanderlust_0
    restart: always

  frontend:
    image: "nabin011011/wanderlust-frontend:latest"
    container_name: "frontend"
    environment:
      - VITE_API_PATH=http://52.66.245.164:5000
    ports:
      - "5173:5173"
    networks:
      - wanderlust_0
    restart: always

networks:
  wanderlust_0:
    name: "wanderlust"
    driver: bridge
